list1=["apple","orange","banana","banana","pineapple"]
x=list1.count("banana")
print("count is ",x)
print(len(list1))
print(min(list1))
print(max(list1))
print("apple" in list1)
print("aaaaa" in list1)
print("apple" not in list1)
list1.sort()
print(list1)
